version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "Europe/Helsinki"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "Europe/Helsinki"
    groups:
      ffmpeg:
        patterns:
          - "Xabe.FFmpeg"
          - "Xabe.FFmpeg.Downloader"
