version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:00"
      timezone: "Europe/Helsinki"
  - package-ecosystem: "nuget"
    directory: "/VideoConverter"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:00"
      timezone: "Europe/Helsinki"
  - package-ecosystem: "nuget"
    directory: "/FFmpegDownloader"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:00"
      timezone: "Europe/Helsinki"
  - package-ecosystem: "nuget"
    directory: "/Tests"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:00"
      timezone: "Europe/Helsinki"
