name: test
on:
  pull_request:
    branches:
      - main
    paths:
      - "**.cs"
      - "**.csproj"
      - ".github/workflows/test.yaml"
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: ["8.0.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build app
        run: dotnet build
      - name: Download FFmpeg executables
        run: dotnet run --project FFmpegDownloader $GITHUB_WORKSPACE
      - name: Set downloaded executables to PATH
        run: echo $GITHUB_WORKSPACE >> $GITHUB_PATH
        shell: bash
      - name: Test
        run: dotnet test
